services:
  pz-dashboard:
    build: .
    volumes:
      - /backups/firestore:/backups
      - /agents_map:/app/app/static/agents_map
      - ./data:/app/app/instance
      - ~/attachments/assets:/app/attachments/assets
    environment:
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - HUBSPOT_AGENT_ASSIGNMENT_TOKEN=${HUBSPOT_AGENT_ASSIGNMENT_TOKEN}
      - SSCC_TOKEN=${SSCC_TOKEN}
      - SFTP_USERNAME=${SFTP_USERNAME}
      - SFTP_PASSWORD=${SFTP_PASSWORD}
      - MEXAL_DOMAIN=${MEXAL_DOMAIN}
      - MEXAL_USER=${MEXAL_USER}
      - MEXAL_PASSWORD=${MEXAL_PASSWORD}
      - MEXAL_COMPANY=${MEXAL_COMPANY}
      - MEXAL_YEAR=${MEXAL_YEAR}
      - INFO_EMAIL_NAME=${INFO_EMAIL_NAME}
      - INFO_EMAIL_ADDRESS=${INFO_EMAIL_ADDRESS}
      - INFO_EMAIL_PASSWORD=${INFO_EMAIL_PASSWORD}
      - FIREBASE_SA_JSON=${FIREBASE_SA_JSON}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend
      - proxy_net
      - db_net

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    restart: unless-stopped
    networks:
      - backend

  sqlite-web:
    image: coleifer/sqlite-web
    restart: unless-stopped
    volumes:
      - ./data:/app/app/instance
    command: sqlite_web -H 0.0.0.0 /app/app/instance/database.db
    environment:
      - SQLITE_WEB_PASSWORD=${SQLITE_WEB_PASSWORD}
    networks:
      - proxy_net

networks:
  backend:
    name: shared_backend
  proxy_net:
    external: true
  db_net:
    external: true

volumes:
  redis_data: